2018-05-21 19:16:20,318 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:52]
2018-05-21 19:16:22,487 ERROR: Exception on /edit_profile [GET] [in /home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/shigaki/microblog/app/routes.py", line 159, in edit_profile
    form=form, photo=photo)
NameError: global name 'photo' is not defined
2018-05-21 19:16:24,921 ERROR: Exception on /edit_profile [GET] [in /home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shigaki/microblog/venv/local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/shigaki/microblog/app/routes.py", line 159, in edit_profile
    form=form, photo=photo)
NameError: global name 'photo' is not defined
2018-05-21 19:17:04,352 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:52]
2018-05-21 19:24:30,725 INFO: Microblog startup [in /home/shigaki/microblog/app/__init__.py:52]
2018-05-21 22:18:36,513 INFO: Microblog startup [in C:\Users\user\microblog\app\__init__.py:52]
